version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    command: gunicorn recipes_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
