# Generated by Django 5.1.6 on 2025-02-25 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.JSONField(help_text='Список ингредиентов в формате JSON')),
                ('steps', models.JSONField(help_text='Список шагов приготовления')),
                ('cooking_time', models.IntegerField(help_text='Время готовки в минутах')),
                ('categories', models.JSONField(blank=True, help_text='Список категорий', null=True)),
                ('time_type', models.CharField(blank=True, choices=[('fast', 'Fast'), ('slow', 'Slow')], max_length=10, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
