# Generated by Django 5.1.6 on 2025-02-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Общее время готовки в минутах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(help_text="Список шагов приготовления. Каждый шаг должен быть объектом с обязательным ключом 'description' и опциональным числовым ключом 'time' (в минутах)."),
        ),
    ]
